FROM alpine:3.23@sha256:5b10f432ef3da1b8d4c7eb6c487f2f5a8f096bc91145e68878dd4a5019afde11 as build

RUN  apk --update add git make mise

ARG  BUILD_DIR=/src/cciu

WORKDIR $BUILD_DIR

COPY . .
RUN  mise trust
RUN  env CGO_ENABLED=0 mise -E build exec go -- make cciu

###

FROM alpine:3.23@sha256:5b10f432ef3da1b8d4c7eb6c487f2f5a8f096bc91145e68878dd4a5019afde11
ARG  BUILD_DIR=/src/cciu
RUN  apk --update add ca-certificates
COPY --from=build $BUILD_DIR/bin/cciu /usr/bin/cciu
