FROM alpine:3.22 as build

RUN  apk --update add git make mise

ARG  BUILD_DIR=/src/cciu

WORKDIR $BUILD_DIR

COPY . .
RUN  mise trust
RUN  env CGO_ENABLED=0 mise -E build exec go -- make cciu

###

FROM alpine:3.22
ARG  BUILD_DIR=/src/cciu
RUN  apk --update add ca-certificates
COPY --from=build $BUILD_DIR/bin/cciu /usr/bin/cciu
