---
version: "2"
linters:
  disable:
    - errcheck
  enable:
    - bodyclose
    - funlen
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - govet
    - lll
    - misspell
    - mnd
    - prealloc
    - staticcheck
    - tagalign
    - wastedassign
  exclusions:
    rules:
      - source: "^func main"
        linters:
          - funlen
      - source: "^func fetchAndCompare"
        linters:
          - funlen
      - path: '.*_test\.go'
        linters:
          - gosec
      - path: 'pkg/imagespec/imagespec.go'
        linters:
          - lll
      - path: 'pkg/imagespec/.*_test.go'
        linters:
          - goconst

  settings:
    funlen:
      ignore-comments: true
    goconst:
      min-occurrences: 4
    mnd:
      ignored-numbers: []
